const $=id=>document.getElementById(id),{escape:e,money,date}=ReceiptsCore;
const id=new URLSearchParams(location.search).get('id');
const member=RECEIPTS_DATA.politicians.find(p=>p.id===id),race=RECEIPTS_RACES.races.find(r=>r.memberId===id);
const displayName=name=>name.includes(',') ? (name.split(',').slice(1).join(' ').trim()+' '+name.split(',')[0]).replace(/\b(?:MR|MRS|MS)\.?\s*/g,'').replace(/\s+/g,' ').trim() : name;
function source(label,url){if(!/^https:\/\/www\.fec\.gov\//.test(url||''))return;const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=label+' ↗';$('sources').append(a);}
function mini(p,label){const f=p.finance||{},value=f.status==='available'?f.otherCommitteeContributions:null;return `<section class="mini-card ${value===0?'zero':value===null?'unknown':''}"><span class="tag">${label} · ${e(p.party)}</span><h2>${e(displayName(p.name))}</h2><p>Other political committees</p><strong>${money(value)}</strong><small>${date(f.coverageStart)} — ${date(f.coverageEnd)}</small></section>`;}
function render(){const p=race.candidates.find(p=>p.fecId===$('opponent').value);if(!p)return;$('pair').className='pair';$('pair').innerHTML=mini(member,'MEMBER')+mini(p,'REGISTERED');$('member-heading').textContent=member.name;$('opponent-heading').textContent=displayName(p.name);$('rows').replaceChildren();for(const [label,key] of [['Individual contributions','individualContributions'],['Other political committees','otherCommitteeContributions'],['Party committees','partyCommitteeContributions'],['Total receipts','receipts']]){const tr=document.createElement('tr');tr.innerHTML=`<th scope="row">${label}</th><td>${money(member.finance?.status==='available'?member.finance[key]:null)}</td><td>${money(p.finance?.status==='available'?p.finance[key]:null)}</td>`;$('rows').append(tr);}const mf=member.finance,pf=p.finance;$('period-warning').textContent=mf.status!=='available'||pf.status!=='available'?'A campaign report is unavailable. Missing data is not zero.':mf.coverageEnd!==pf.coverageEnd||mf.coverageStart!==pf.coverageStart?'Different reporting periods. These amounts are not a like-for-like comparison.':'Both reports cover the same period. Amounts describe these campaigns, not personal income.';$('sources').replaceChildren();source('Member’s FEC record',member.sourceUrl);source('Candidate’s FEC record',p.sourceUrl);source('View the FEC race',race.sourceUrl);}
if(!member||!race){$('empty').hidden=false;$('empty').textContent='This member could not be found. Open a receipt and choose Compare again.';}
else{$('seat').textContent=`${race.state} · ${race.office}${race.district!==null?` district ${race.district}`:''} · ${race.electionYear}`;if(race.status==='registered-candidates'&&race.candidates.length){$('comparison').hidden=false;for(const p of race.candidates){const option=document.createElement('option');option.value=p.fecId;option.textContent=`${displayName(p.name)} — ${p.party}`;$('opponent').append(option);}$('opponent').addEventListener('change',render);render();}else{$('empty').hidden=false;$('empty').textContent=race.status==='not-up-this-cycle'?`${member.name}’s regular Senate seat is not up for election in ${race.electionYear}. No opponent comparison is shown for this cycle.`:race.note;source('View the FEC race',race.sourceUrl);source('Member’s FEC record',member.sourceUrl);}}

$('snapshot-date').textContent=`Finance snapshot ${date(RECEIPTS_RACES.meta.financeRetrievedAt)} · registrations snapshot ${date(RECEIPTS_RACES.meta.retrievedAt)} · bundled records, not live.`;
