const person = RECEIPTS_DATA.politicians.find(p => p.id === new URLSearchParams(location.search).get('id'));
const receipt = document.getElementById('receipt');
document.title = person ? `${person.name} - Receipts` : 'Member not found - Receipts';
if (!person) {
  receipt.innerHTML = '<p class="missing-record">Member not found in this snapshot. <a href="index.html">Find a member of Congress</a>.</p>';
  document.getElementById('member-name').textContent = 'Member not found';
  document.querySelector('.record-notes').hidden = true;
} else {
  const {escape:e,money,date,partyKind} = ReceiptsCore;
  const f = person.finance || {}, available = f.status === 'available';
  const amount = key => money(available ? f[key] : null);
  document.getElementById('member-name').textContent = person.name;
  document.getElementById('record-id').textContent = person.id;
  document.getElementById('member-meta').innerHTML = `${e(person.state)} · ${e(person.chamber)} · <span class="party-label" data-party="${partyKind(person.party)}">${e(person.party || 'Party not reported')}</span>`;
  receipt.innerHTML = `<article class="player-card profile-card" data-party="${partyKind(person.party)}">
    <div class="card-hero profile-top"><h2>Campaign funding</h2><span>${e(person.party || 'Party not reported')}</span></div>
    <div class="funding-main"><p>Total reported receipts</p><strong class="funding-total">${amount('receipts')}</strong><p id="record-period">${date(f.coverageStart)} – ${date(f.coverageEnd)}</p><p class="short-note">Includes more than donations. Transfers can be counted twice.</p>
    ${!available ? `<p>${e(f.unavailableReason || 'Campaign summary unavailable.')} Unknown does not mean zero.</p>` : ''}
    <dl class="funding-split"><div><dt>From individuals</dt><dd>${amount('individualContributions')}</dd></div><div><dt>From other political committees</dt><dd>${amount('otherCommitteeContributions')}</dd></div><div><dt>From party committees</dt><dd>${amount('partyCommitteeContributions')}</dd></div></dl>
    <details class="record-detail"><summary>Small and large donations · unavailable</summary><p>This snapshot has no donor-size split. Itemized contributions are not automatically large donations.</p></details>
    <details class="record-detail"><summary>Lobbyist money · unavailable</summary><p>Lobbyist contributions and lobbyist-bundled contributions require separate records. Political committee money is not a lobbyist total.</p></details>
    <details class="record-detail"><summary>Accounting and sources</summary><p>This is the FEC candidate summary for ${e(person.fecId || 'an unavailable candidate ID')}, combining authorized committees. Receipts may include loans and transfers; contributions below are not a complete breakdown of receipts. Transfers received: ${amount('transfersFromAuthorized')}. Transfers sent: ${amount('transfersToAuthorized')}.</p><p>Snapshot: <span id="record-snapshot">${date(RECEIPTS_DATA.meta.retrievedAt)}</span>. Missing means unknown.</p><p><a href="${e(person.sourceUrl || 'https://www.fec.gov/data/candidates/')}">Candidate’s FEC record</a> · <a href="https://www.fec.gov/campaign-finance-data/all-candidates-file-description/">Field definitions</a></p></details>
    <a class="compare-action" href="compare.html?id=${encodeURIComponent(person.id)}">Compare campaign records <span aria-hidden="true">→</span></a></div></article>`;
  const records = globalThis.RECEIPTS_RECORDS;
  const roll = records?.rollCall, vote = roll?.votes[person.id];
  const report = records?.investmentReports.find(r => r.memberId === person.id);
  const history = document.querySelector('.record-notes');
  const trades = report ? report.transactions.map(t => `<li class="transaction"><div><strong>${e(t.asset)} <span class="ticker">${e(t.ticker)}</span></strong><span>${date(t.date)}</span></div><p>${e(t.action)} · ${e(t.assetType)} · ${e(t.owner)}</p><strong>${money(t.amountMin)} – ${money(t.amountMax)}</strong><details><summary>Transaction details and source</summary><p>${e(t.description)}</p><p>Reported range, not an exact price. Not current holdings or profit.</p><a href="${e(report.url)}#page=${t.sourcePages[0]}">Official report · row ${e(t.id.split(':')[1])}, page ${t.sourcePages.join(' / ')}</a></details></li>`).join('') : '';
  history.innerHTML = `<section class="history-section"><p class="kicker">PUBLIC DECISIONS</p><h2>A recorded vote</h2>${vote ? `<p class="vote-result">${e(vote)}</p><h3>${e(roll.bill)} · ${e(roll.title)}</h3><p>Motion to agree with the Senate amendment.</p><p>${date(roll.date)} · House roll call ${roll.number}</p><details><summary>What was voted on?</summary><p>${e(roll.question)}. The motion ${e(roll.result.toLowerCase())}.</p><p>This records a vote on this motion, not every provision or a reason for the member’s decision.</p><a href="${e(roll.url)}">Official House roll call</a></details>` : `<p>${person.chamber === 'Senate' ? 'Senate votes are not included in this review.' : 'No matched entry in the selected House vote.'}</p>`}<p class="short-note">One selected vote. A complete voting history is not included.</p></section>
    <section class="history-section"><p class="kicker">FINANCIAL DISCLOSURES</p><h2>Reported investments</h2>${report ? `<p>9 transactions · <strong>Spouse</strong></p><p>Report filed ${date(report.filed)}. Transactions dated Dec 20, 2024 – Jan 14, 2025.</p><details class="all-transactions"><summary>Read all 9 reported transactions</summary><ol class="transactions">${trades}</ol></details><p class="short-note">One selected original report. Later reports and amendments are not reconciled; this is not a complete trading history.</p><a href="${e(report.url)}">Read the official disclosure</a>` : '<p>No investment report included for this member.</p><p class="short-note">This does not mean the member has no investments or transactions.</p>'}</section>
    <details class="record-detail coverage-detail"><summary>About this review’s coverage</summary><p>Funding uses the September 8, 2026 snapshot. Votes cover one House roll call from July 3, 2025, joined by exact Bioguide ID, chamber and state. Investments cover one manually verified Pelosi disclosure, joined by filer and district. Each record keeps its own date.</p><p>These records do not establish motive, influence, misconduct or a link between a trade and a vote.</p><a href="privacy.html">Full methodology</a></details>`;
}
